---
name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 1.1)'
        required: true

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.1"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/plant_sense"
          zip plant_sense.zip -r ./

      - name: Commit and tag
        working-directory: ${{ github.workspace }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ inputs.version }}"
          git push origin tag "v${{ inputs.version }}"

      - name: "Upload the ZIP file to the release"
        uses: "softprops/action-gh-release@v3.0.1"
        with:
          files: |
            ${{ github.workspace }}/custom_components/plant_sense/plant_sense.zip
